### ISSUE TITLE
Abount nsNMF using nmfgpu4R

### ISSUE THREAD

**Issue by kuchewen** [razorx89/nmfgpu4R#2]
HI
In normal , if we use '"nsNMF" algorithm, we can get the matrix W which column sum are equal to 1.But I use nmfgpu4R by nsNMF algorithm, why the column sum of  matrix W are not equal to 1?
Thanks.

**Comment by razorx89** [comment]
This is mainly because of an API design issue in nmfgpu, which I have on my todo list for quite long. nmfgpu currently only supports to return two matrices and  since nsNMF is a tri-factor nmf algorithm I have to mix the smoothing matrix S into on of the other factor matrices. As stated in the nsNMF paper, it is legit to either compute `W'=W*S` and `H'=H` or `W'=W` and `H'=S*H`. I am currently using the first method which is why the column sums of W are not normalized anymore.

**Comment by kuchewen** [comment]
Gotcha.Thanks a lot :)
